# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 913c90d8f42c6ad4b8dc00bdb2b286b5304a4632efdc08c6040bc3739d98f6a2cbdde01bf78b30225e1d9ca375fd69015a0206d3876d071d8784f71209ee5f15

test:
  secret_key_base: bf8dffed51e88137d39d85f708d1db588afdf0bc496508005bcf94da7f88fcb770f08466fc72814c5877d35c33968f4350b7dc16accae60e4fd2df3bfbe72efe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
